---
- name: install python 3
  apt: >
    pkg={{item}}
    state=latest
    update_cache=true
    cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - python3
    - python3-venv
  become: yes