---

# Create environment variables for development
# Same variable must present on heroku

- name: Set server type
  lineinfile: dest=/etc/environment
              line='SERVER_TYPE={{group_names[0]}}'
  become: yes


- name: Set secret key
  lineinfile: dest=/etc/environment
              line='SECRET_KEY={{secret_key}}'
  become: yes

- name: Set database name
  lineinfile: dest=/etc/environment
              line='DATABASE_NAME={{db_name}}'
  become: yes

- name: Set database user
  lineinfile: dest=/etc/environment
              line='DATABASE_USER={{db_user}}'
  become: yes

- name: Set database password
  lineinfile: dest=/etc/environment
              line='DATABASE_PASSWORD={{db_password}}'
  become: yes

- name: Set cloudinary cloud name
  lineinfile: dest=/etc/environment
              line='COUDINARY_CLOUD_NAME={{coudinary_cloud_name}}'
  become: yes

- name: Set cloudinary cloud name
  lineinfile: dest=/etc/environment
              line='CLOUDINARY_API_KEY={{cloudinary_api_key}}'
  become: yes

- name: Set cloudinary cloud name
  lineinfile: dest=/etc/environment
              line='CLOUDINARY_API_SECRET={{cloudinary_api_secret}}'
  become: yes

- name: Set Debug
  lineinfile: dest=/etc/environment
              line='DEBUG=True'
  become: yes
