---
- name: remove existing environmrent
  file: path={{ virtualenv }}
        state=absent

- name: install python 3
  apt: >
    pkg={{item}}
    state=latest
    update_cache=true
    cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - python3-dev
    - libxslt1-dev
    - zlib1g-dev
  become: yes

- name: create fresh environment
  pip:
    requirements: "{{ project_root }}/requirements.txt"
    virtualenv: "{{ virtualenv }}"
    virtualenv_command: "{{ virtualenv_command }}"